story = [{
    "lesson_screen_id": 115855,
    "lesson_id": 385,
    "title": "Sports Scholarship",
    "content": "You could be one of those people who perform very well when it comes to sports. If you are and you happen to be in high school, you may be thinking that your ability at a given sport could end up putting you in line for a sports scholarship that will pay for your college education either in its entirety or, at the very least, partially. However, there is more to getting a scholarship than just being good at sports. One thing you have to keep in mind is that, with sports scholarships, there are a number of ways to obtain them. For some athletes, especially within the more high-profile sports of football and basketball, there is a good chance of being recruited. Not all scholarships that are sports-related come from athletes being recruited, however. In many cases, if you are looking for a sports scholarship for the sport you happen to play, you may have to call recruiters and ask. It is possible that your talents at a given sport are far above most people; however, with so many excellent high school athletes out there, there is still the possibility of being overlooked. There are too many athletes and only a limited number of coaches and recruits, comparatively speaking. In some cases, you will have to contact a coach yourself and offer them your statistics on the field, as well as your academic data as well. Nevertheless, if you have the abilities, the drive, the talent and, of course, the grades, you will eventually find a sports scholarship that fits your needs. The truth is, there are plenty of sports scholarships to go around. Some may be full scholarships while others may be partial; be wise and don't get too far ahead of yourself by only going after full scholarships as your only option. While they do exist, they are not easy to obtain and, when it comes to paying for college nowadays, any help is more than welcome... or at least, it should be.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 0,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115856,
    "lesson_id": 385,
    "title": "Mountain Biking",
    "content": "The sport of mountain biking is one of the best active sports you can partake in for a number of fitness reasons. Depending on what style of mountain biking you enjoy, it can also be a great deal of fun while keeping you fit at the same time. People are usually unaware of how many muscles they use when riding a mountain bike and how quickly they burn calories; it can be an extremely good workout for the body. If you plan on riding cross-country along different types of trails, riding a bike can be quite a task. If you're riding over long distances up and down hills it can be very tiring for the legs and lower back. So if you are just starting to ride bikes for the first time, please don't just jump on the bike and go for a 20-mile ride as it may do you more harm than good. One recommendation is to begin by going on short rides of only a couple of miles, which take no time at all, in order to get your fitness training up to a higher level before embarking on longer rides. All the major athletes in the sport will tell you that training is important and you should take part in mountain bike fitness training whenever an opportunity arises. One of the greatest benefits of riding a mountain bike on a regular basis is that bike riding engages some of the largest muscles in the body which, in turn, burns off fat quickly. This will, of course, help you to lose weight and the more you ride your bike, the more weight you will lose. When you ride your bike on flat ground at a slower speed, you will still burn a great number of calories due to the fact that you will be able to continue pedaling for longer periods. This is also perfect for people who don't have the stamina for highly-intensive rides at different speeds and climbs.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 1,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115857,
    "lesson_id": 385,
    "title": "They're Minerals, Marie!",
    "content": "Sedimentary rocks are formed at the surface of the Earth, either in water or on land. They are layered accumulations of sediments, fragments of rocks, minerals, or animal or plant material. If a layer of sediment is buried beneath overlying rock, the layer becomes compacted and may form a layer of sedimentary rock. The sediment becomes cemented together by minerals and chemicals or is held together by electrical attraction. Sand and gravel deposits on beaches or in river bars look like the sandstone and conglomerate they may become. Compacted and dried mud flats harden into shale. Mud and shells settling on sea floors can cement into limestone. Sedimentary rocks are important sources of natural resources like coal, fossil fuels, drinking water or ores. Fire is a chemical reaction between fuel and oxygen. Heat is necessary to ignite the reaction. Once a fire has been started, it creates enough heat as a byproduct to keep igniting new fuels. In nature, fuels can be preheated by the sun. This can make them more likely to ignite, either by human error, as with a dropped cigarette or unattended campfire, or by lightning. Fuels themselves are abundant, especially in forests that have not burned in recent years. Oxygen is readily available in the air we breathe. It has about 21% oxygen in it. The positive effects of fire include stimulating growth and maintaining various ecological systems. The negative effects include water contamination, soil erosion, atmospheric pollution and hazard to human and animal life. An earthquake is the result of a sudden release of energy in the Earth's crust producing seismic waves. Earthquakes occur most often along geological faults. They are measured using observations from seismometers. Magnitude 3 or lower earthquakes are mostly undetectable and magnitude 7 or greater can cause serious damage over large areas, depending on their depth. The shallower an earthquake, the more damage to structures it causes. At the Earth's surface, earthquakes manifest themselves by shaking and sometimes displacing the ground. When the epicenter of a large earthquake is located offshore, the seabed may be displaced sufficiently to cause a tsunami. Earthquakes can also trigger landslides and volcanic activity.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 2,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115858,
    "lesson_id": 385,
    "title": "Hypno Toad",
    "content": "Tiny poison dart frogs may be only one inch long but they pack a powerful punch of poison. Weighing less than an ounce, these frogs are considered one of Earth's most toxic species. For example, the golden poison dart frog has enough poison to kill 20,000 mice. With a range of bright colors, yellows, oranges, reds, greens, and blues, they aren't just big show-offs, either. Those colorful designs tell potential predators, \"I'm toxic; don't eat me.\" Scientists believe that poison dart frogs get their toxicity from some of the insects they eat. The insects feed on plants that have toxins, which they then pass on to the frogs who fed on them. Poison dart frogs raised in captivity aren't toxic because the insects they are fed haven't eaten poisonous plants. How do poison dart frogs capture their prey? With a long, sticky tongue that darts out and zaps the unsuspecting bug! The frogs eat many kinds of small insects, including fruit flies, ants, and tiny beetles, which are the ones scientists think may be responsible for the frogs' toxicity. Poison dart frogs live in the rain forests of Central and South America and breed during the rainy season. To attract a female, the male frog calls from a leaf, making buzzing or trilling sounds. After he's attracted a mate and she lays her eggs, the male sticks around to make sure the eggs stay moist until they hatch. Once the little ones hatch as tiny tadpoles, they wiggle on to the male's back. He carries them to a pool of water where the tadpoles wiggle off and complete their metamorphosis into fully-formed frogs.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 3,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115862,
    "lesson_id": 385,
    "title": "Titanic Lessons",
    "content": "In 1912, Titanic is the largest artificial moving object in the world. She is as long as four city blocks and wider than a four-lane highway. Some people say she is unsinkable. No expense has been spared to build her. She is grand in every way. Many wealthy and important people are aboard to experience the one-of-a-kind voyage. Tonight, the water is calm and looks as smooth as glass. Yet, there may be danger. Suddenly, something is seen ahead. It looks dark against the starry sky. It's big and it's close. Iceberg right ahead! Titanic travels ever nearer to the iceberg. Slowly, the ship begins to swing away. It looks like the ship might miss the iceberg after all. Then comes a grinding sound. Under the water, the iceberg is much wider than it looks. Titanic scrapes against it. The iceberg has slashed holes in the side of one of the furnace rooms. As water gushes through the holes, it nearly sweeps the crewmen off their feet. Within minutes, the cold, swirling seawater is up to their waists. Seawater is also gushing through holes torn into other sections of the ship. Titanic's hull has 16 sections. Doors can seal off each section if they are damaged. The officer on the bridge orders all the doors closed. He hopes this will prevent disaster. He doesn't know that it's already too late. The doors slow, but cannot stop, the water because the walls don't reach the ceiling. As seawater fills each section, the water spills over the wall into the next section. The first five sections soon fill with water.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 4,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115860,
    "lesson_id": 385,
    "title": "Chubby Bunny",
    "content": "As the number of overweight children in the United States continues to climb, fitness is a consideration that weighs heavily on the minds of parents, caregivers, and teachers. The risk of health issues accompanying obesity among children provokes many fears that unless parents and children make significant changes in the lifestyles practiced by our kids, diabetes, heart disease, and other weight-related conditions have the potential to run rampant among American youth. Although encouraging a healthy lifestyle among children, including physical activity and fitness is vital to addressing issues associated with health problems and obesity; the addition of kid's fitness can also promote a lifelong love. Fitness not only encourages physical activity, keeping weight and accompanying conditions at bay, it also helps protect children from injuries that can occur when they are not accustomed to physical activity, movement, and sports. Most injuries that plague children completing physical activities occur as a result of a lifestyle that lacks movement and activity that can provide balance, coordination, and muscle memory necessary for a fit lifestyle. Despite statistics praising physical activity among children as a weight management tool and method of decreasing injuries during activities and sports, fitness among children boasts a plethora of positive results and side effects. Strong bones and joints, stress relief, self-confidence improvement, and better academic concentration are just some of the other benefits touted by a child's active lifestyle. Understanding what types of activities and scheduling conflicts are preventing a child from obtaining a sufficient amount of physical activity and fitness can be a good way for parents to begin to understand how and where transformations can be made regarding kids' health. Tracking the amount of activity a child partakes in can be as simple as gaining an awareness of their school schedules and whether they include physical education classes, recess, and other ways children participate in fitness-centered activities. Children who participate in a variety of physically demanding activities at school, such as extracurricular athletics or PE classes, may not need as much prompting and extra fitness added to their day as a child who spends more time still and sedentary. One of the best ways parents, caregivers, and teachers can prompt children to compete in fitness activities and grasp a healthy lifestyle is by striving toward adopting a similar lifestyle that promotes and values physical activity themselves. Children with even one obese parent have a 50 percent chance of being obese themselves. Children with two obese parents have an 80 percent chance of following in their footsteps. Children who observe healthy lifestyles in their parents and role models have a better chance of adopting similar habits, highlighting the vital role parents play in influencing the fitness levels and physical activity of children.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 5,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115863,
    "lesson_id": 385,
    "title": "Iceland",
    "content": "Hike through one of Iceland's many ancient lava fields. You might notice something strange. The ground in front of you is steaming. Plumes of white steam rise from the ground. Iceland is covered with steam vents and hot springs. The steam comes from naturally-heated rocks and hot water below Earth's surface. The most famous of Iceland's bubbling hot springs is Blue Lagoon. It is not far from the country's capital city. You can visit the lagoon and soak in its soothing, milky blue waters. Minerals and white mud in the water make your skin as soft as a newborn baby's skin. Icelanders tap into the natural hot water for more than soaking. They harness steam from hot water to spin turbines and create electricity. People use the electricity to heat homes and even greenhouses.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 6,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115864,
    "lesson_id": 385,
    "title": "Gitbox",
    "content": "Learning to play the guitar can be an extremely rewarding experience, but it is made even more so if you find the right teacher who will also guide to help you achieve your musical goals with the right resources. The best teachers always prepare and have a plan. In teaching, it is said that, for every hour of teaching, teachers need to prepare twice as much. You should be able to tell whether you're dealing with a professional in your first meeting. They will determine where you are, where you want to go, and then propose a method for getting you there. If you can tell that your prospective teacher hasn't prepared for the lesson and looks like they are making up stuff on the spot, they probably are. Get away as fast as you can.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 7,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115865,
    "lesson_id": 385,
    "title": "Water",
    "content": "Water covers 70 percent of Earth's surface, yet most of it is unusable, which is why many people around the world struggle to get enough of it. Nearly 97 percent is salty or otherwise undrinkable. Another two percent is locked up in glaciers and ice caps. That leaves only one percent. People, plants, and animals depend on that one percent of fresh water. Each drop of water is always on the move. The water we drink is a liquid. It can also be a solid or a gas. No matter what state of matter it's in, all water is connected. It constantly moves through an endless cycle above, on, and through Earth. The amount of water on our planet never changes. There is the same amount now as there was when Earth formed.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 8,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 115866,
    "lesson_id": 385,
    "title": "Death Valley",
    "content": "Valuable ores lay hidden beneath Death Valley. These treasures included gold and silver. When miners gave up on the goldfields in other parts of California, many came to the desert. Most mining settlements followed a predictable pattern. First came the prospectors. They searched for gold deposits. When they made a strike, they staked a claim. Then they either worked the claim themselves or sold it. Miners came to Death Valley for more than gold. Some came to mine a kind of salt. People used the salt to make a substance called borax. It was used to make glass, ceramics, and cleaning products.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 9,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405860,
    "lesson_id": 385,
    "title": "Amalaki Tree",
    "content": "For years, health enthusiasts have lived by the age-old motto, \"an apple a day keeps the doctor away.\" While it's true that an apple provides ample vitamin C as well as antiallergenic, anti-inflammatory, and antiviral benefits, there's an even more powerful fruit that contributes to your overall health. The Amalaki tree, which is primarily found in the tropical areas of Asia, has been cultivated in gardens for centuries and has sprung up as a popular commercial crop that's grown for medicinal purposes. Amalaki is a fruit that can really keep the doctor away.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 10,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405861,
    "lesson_id": 385,
    "title": "Hero Shrew",
    "content": "At only a few inches long and with no distinctive external features to speak of, the Hero Shrew is seemingly an unremarkable creature. That is, until you accidentally step on one. You see, the Hero Shrew can comfortably survive being stood on by a typical adult human without any injury. The secret to this skill lies in the Shrew's skeletal system or, more specifically, its spine. Unlike almost every other mammal on Earth, with one notable exception which we'll get to in a moment, the Hero Shrew's spine features intricate interlocking vertebrae, a very large number of spinal processes, and is incredibly thick relative to the size of its total body weight.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 11,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405862,
    "lesson_id": 385,
    "title": "Dog Agility Training",
    "content": "Dogs often love attending a dog agility training class. They're given the opportunity to work in a new environment with ramps, jumps, poles, and tires that are often colorful and inviting. To be a part of a dog agility training class, most groups will require that you've previously attended and completed an obedience class for your dog and many will ban your pet from participation if it's an aggressive animal. Usually, a dog agility class will run for about an hour once a week, for a course of six weeks. Classes begin with warm-ups and playtime to get the dog acclimated to its surroundings.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 12,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405863,
    "lesson_id": 385,
    "title": "Highway Driving Tips",
    "content": "When you're on the highway, use cruise control, which helps maintain a constant speed. Use the highest gear possible and overdrive gears if you have them. The faster an engine is turning, the more gas you're using. Pay attention to your tachometer. Plus, a slower turning engine means less friction and engine wear. Avoid excessive idling. Idling gets zero miles per gallon. It doesn't get much worse than that. If you're stopped for a train or backed up in a fast food take-out line or waiting for a drive-thru bank teller, stop your engine if you're going to be idling for more than 30 seconds.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 13,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405864,
    "lesson_id": 385,
    "title": "Fuel Efficiency",
    "content": "The faster you drive, the more fuel you're using. 55 mph is the optimum speed on the highway. Authorities are again considering making 55 mph required on all highways in an effort to mandate fuel conservation. If they do that, you'll be well ahead of the game. On some highways in West Texas, you can legally drive 80 mph. Gas mileage drops dramatically at this speed. Don't drive erratically. Strive for smooth starts and stops. Pick a lane and stay in it without weaving in and out of traffic. The shortest distance between two points is a straight line.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 14,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405865,
    "lesson_id": 385,
    "title": "Frank Bickerton",
    "content": "Frank Bickerton spent most of the 1912 winter working to convert it to a sledge, fashioning brakes from a pair of geological drills and a steering system from the plane's landing gear. It was first tested on the 15th of November, 1912 and subsequently assisted in laying depots for the summer sledging parties, but its use during the expedition was minimal. Towing a train of four sledges, the air tractor accompanied a party led by Bickerton to explore the area to the west of the expedition's base at Cape Denison. The freezing conditions resulted in the jamming of the engine's pistons after just 10 miles, and the air tractor was left behind. Later, it was dragged back to Cape Denison, and its frame was left on the ice when the expedition returned home in 1913.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 15,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405866,
    "lesson_id": 385,
    "title": "Oil and Water",
    "content": "Oil and water don't mix. You have probably heard this old saying. It isn't just folk wisdom, however. It's chemistry. Another common expression, \"like water off of a duck's back,\" illustrates the same basic principle. The oil on a duck's feathers repels water and prevents the bird from getting soaked in the rain. Naturally oily feathers also help keep a bird dry as it swims. Chemistry is just one way to repel water in nature. Structure, or the shape of things, is another. To excel at water repellency, the lotus leaf relies on both. Unlike water lilies, the lotus holds its leaves and flowers high above a pond's surface. Still, each lotus is amply prepared to fend off a drenching. The waxy surface of the leaves helps repel water chemically.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 16,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405867,
    "lesson_id": 385,
    "title": "Vegetable Gardening",
    "content": "Vegetable gardening requires a lot more work than herb gardening. In fact, vegetable gardening can be one of the most time-consuming types of gardening. Many vegetables require watering and fertilizing at regular intervals, and may require a lot of different types of maintenance. Some vegetables are hardier and less picky than others. You can find some types of vegetables that don't require a lot of work at all so you can still find vegetable gardening a fun and relaxing hobby if you're careful to choose varieties that don't require constant attention. Some people may especially enjoy vegetable gardening because they love the satisfaction of growing some of their own food.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 17,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405868,
    "lesson_id": 385,
    "title": "Carbon Dioxide",
    "content": "Carbon dioxide is a chemical compound that is usually in the form of a gas. It is made up of one atom of carbon and two atoms of oxygen. Carbon dioxide was discovered by a Belgian chemist named Jan Baptista van Helmont. Carbon dioxide is necessary for life on Earth. When animals breathe out, they release carbon dioxide into the air. Plants use this carbon dioxide to make their own food in a process called photosynthesis. Plants then release oxygen into the air for animals to breathe in. Carbon dioxide also is an essential part of Earth's atmosphere. It plays an important role as a greenhouse gas. A greenhouse gas traps energy from the Sun, which warms Earth's surface. This is known as the greenhouse effect.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 18,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405869,
    "lesson_id": 385,
    "title": "Crayons",
    "content": "The crayon is a drawing implement made of clay, chalk, plumbago, dry color, and wax. There are two types of crayon: the coloring crayon and the chalk crayon. The coloring crayon, or wax crayon, is the one used by children in making pictures. It consists of waxes such as paraffin, beeswax, and carnauba wax and dry color. Some synthetic waxlike materials are also used in the modern crayon. The waxes are melted and the dry color added with continuous mixing until thoroughly dispersed. Normally, the crayon is entirely consumed during the marking process through abrasion.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 19,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405870,
    "lesson_id": 385,
    "title": "Cockroach Rescue Team",
    "content": "When buildings collapse in future disasters, a robotic cockroach may be the new hero helping rescue people. Disgusting as they may be, roaches have the remarkable ability to squish their bodies down to one quarter their normal size, yet still scamper at lightning speed. Also, they can withstand nine hundred times their body weight without being hurt. That's similar to a two hundred pound man who wouldn't be crushed by ninety tons on his head. The amazing cockroach-inspired scientists to create a mini robot that can mimic those feats of strength and agility. The researchers hope swarms of future roach-like robots could be fitted with cameras, microphones, and other sensors.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 20,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405871,
    "lesson_id": 385,
    "title": "Children's Literature",
    "content": "Books written especially for children are called children's literature. Children's literature includes stories, fairy tales, fables, poems, and novels. It also includes nonfiction works of history, science, and other subjects. Children's literature can come in the form of picture books or chapter books. Picture books usually have a smaller amount of text, or words, and pictures on every page. They are written for younger readers. Chapter books have few or no pictures and much more text, which is divided into sections called chapters. Chapter books are written for older children.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 21,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405872,
    "lesson_id": 385,
    "title": "Two for One",
    "content": "Don't be susceptible to the two-for-a-dollar marketing tool unless it's to your advantage with a coupon. If you need two of the item, go ahead and buy them; but save by buying only one if that's what you need. For example, the sign may read: 15 limes for a dollar. Unless you're a big lime user, some could go bad before you use them. There was a time when some shoppers felt using coupons was not appreciated by the grocer and hesitated to use them. They didn't want to hold up the line while the checker scanned coupons. It's a faster and easier method now with computers.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 22,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405873,
    "lesson_id": 385,
    "title": "Yamagata",
    "content": "The mountains of Japan's Yamagata prefecture are considered sacred by the Buddhists in the region. These holy sites are sparsely populated, their forests interrupted only occasionally by isolated Buddhist temples. Many of the men serving in the temples come seeking solitude and an escape from the modern world. They were probably a bit startled, then, when a group of scientists and historians showed up and asked to see their mummies. The year before, several researchers investigating rumors of local mummies had discovered six mummified Buddhist monks in five temples in Yamagata prefecture. Soon after the discovery, several Japanese universities formed.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 23,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405874,
    "lesson_id": 385,
    "title": "Moon Photography",
    "content": "Make the moon look extra cool by photographing it behind an object near the horizon. Buildings, statues, trees, and hills can all make great foreground subjects. You could also silhouette a person, animal, bicycle, or an airplane flying by. Of course, you'll need to find out what time and in which direction the moon will be rising so you can position yourself and your camera in a good spot. Check the weather forecast! If it's cloudy, you might still be able to capture a cool pic of the moon poking through the clouds. But if the weather's really bad, you could always go out the next night and still get some superb shots!",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 24,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405875,
    "lesson_id": 385,
    "title": "The Gecko",
    "content": "What gives the gecko its grip? What allows it to stick to any surface, even glass? The answer is in its toes. A gecko's toes are wide and flat. Each toe pad is covered with thousands of tiny hairs called setae. Each hair splits apart into even smaller hairs at the tip. These tips can stick to surfaces. To get unstuck, a gecko peels its toes off of the surface, starting with the tip of its toe. A gecko's toe joints can bend in the opposite direction of our fingers and toes. All of this sticking and unsticking happens very fast. A gecko running up a wall might attach and detach its toes 30 times per second.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 25,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405876,
    "lesson_id": 385,
    "title": "Solar Flares",
    "content": "Solar flares often form around sunspots. A solar flare forms when gases and energy explode from the sun's surface. The jet of energy shoots into space. It reaches Earth in just a few days. Colliding with Earth's atmosphere, the energy streams toward Earth's poles. It causes gases in the atmosphere to glow, green, blue, red, and even pink. We call these shimmering colors auroras. Energy from the sun not only warms Earth. It warms all the planets. A planet is a large space object that orbits a star. In all, eight planets orbit the Sun (or nine, for those who count Pluto among them). Four of these planets are small, rocky worlds. They're called the inner planets. The other four are gas giants. They're called the outer planets. (And a dwarf planet, for those who count Pluto.)",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 26,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405877,
    "lesson_id": 385,
    "title": "Melons",
    "content": "Melons are sweet fruits. They have a fragrant, juicy inside that is usually eaten fresh. Melons are a good source of vitamins A and C. Common melons include cantaloupe, honeydew, and casaba. Melons are related to gourds, cucumbers, pumpkins, and squashes. Watermelons also are related, but they are not considered true melons. Melons originally grew in central Asia. Today, people grow them in warm areas throughout the world. Melon plants are annuals. This means they last only one growing season and must be replanted the following year.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 27,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405878,
    "lesson_id": 385,
    "title": "Science Behind Auroras",
    "content": "Auroras are caused by the sun. The sun sends out a stream of electrically-charged particles called the solar wind. The solar wind travels from the sun toward the Earth at great speed. The Earth is a huge magnet surrounded by a magnetic field. The Earth's magnetic field forces the charged particles in the solar wind toward the planet's northern and southern polar regions. The particles move downward through the Earth's upper atmosphere. As they do, they crash into atoms and molecules of gases such as oxygen and nitrogen. These collisions cause the atoms and molecules to give off light. This light is an aurora. An aurora's colors are determined by the different gases that give off the light.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 28,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405879,
    "lesson_id": 385,
    "title": "Aromatherapy",
    "content": "Lemongrass and sage scents, which are also good for fatigue, are known to help some people with headaches. These scents calm the nervous system and relax your inner being, which will minimize the headache that won't allow you to function. Can you believe aromatherapy can even help with your acne issues? Cedarwood, lemon, and sandalwood are effective scents that help promote the body's ability to control its hormonal balance as well as the skin's oil production. Aromatherapy is an excellent solution for those who are looking for alternative treatments to use in minor medical issues.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 29,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405880,
    "lesson_id": 385,
    "title": "Longships",
    "content": "Longships were sea vessels made by Nordic Vikings and used for trade, commerce, exploration, and warfare during the Viking Age. The longship's design evolved over many years, beginning in the stone age with the invention of the Umiak and continuing up to the 9th century with the Nydam and Kvalsund ships. The longship appeared in its complete form between the 9th and 13th centuries. The character and appearance of these ships have been reflected in Scandinavian boat-building traditions until today. The longship is characterized as a graceful, long, narrow, light, wooden boat with a shallow draft hull designed for speed.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 30,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405881,
    "lesson_id": 385,
    "title": "Eating Insects",
    "content": "Today, insects are part of traditional diets throughout much of the world. You don't even have to go to remote places like a rain forest to find bugs on the menu. In Mexico, you can buy grasshoppers by the bag. Just roast and wrap in a tortilla. At the movies in South America, the snack bar might serve roasted ants instead of popcorn. If you wander through a market in Thailand, you'll find bins of deep-fried silkworms and water bugs. A handful makes a perfect snack. Even if you haven't been to these places, you may have eaten bugs, too. You may not have done it on purpose, though. Bug bits end up in such foods as chocolate and peanut butter. In the United States, an average person eats about a pound of insects a year.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 31,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405882,
    "lesson_id": 385,
    "title": "Hubble Telescope",
    "content": "The Hubble Space Telescope is in orbit around Earth as a floating observatory. The Hubble magnifies and records images of distant space objects. It then sends the information to astronomers on Earth. Other spacecraft, both crewed and empty, have also gathered information about the Sun, Moon, and planets. In addition, astronomers use cameras and other instruments to record information about distant objects. Photographs provide astronomers with a visual record of their observations. Other instruments can help reveal faint, hard-to-detect objects in outer space. These instruments measure light and other radiation coming from these objects.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 32,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405883,
    "lesson_id": 385,
    "title": "Gecko Eyes",
    "content": "A gecko can see colors in the dark, which few living creatures can do. A nocturnal gecko's eye structure is different from that of other lizards. Most vertebrates have two kinds of cells in their eyes that sense light. These are called rods and cones. Rods pick up only black and white. Cones detect colors, but only when there's lots of light. Lizards do not have rods, only cones. Geckos that come out at night have three kinds of super-sized cones. These cones give nocturnal geckos their super-color vision. It's important for a gecko to protect its eyesight. Most geckos have no eyelids and cannot blink. If dust gets in a gecko's eyes, it uses its tongue to lick them clean.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 33,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405884,
    "lesson_id": 385,
    "title": "Pursuit of Spices",
    "content": "Communities all over the world use regional spices to further preserve and enhance their foods. The pursuit of spices is even credited with promoting world exploration. Columbus discovered the Americas while looking for new trade routes to access India for its spices. Today, food additives have advanced well beyond their early rudimentary uses. We still use salt and vinegar to preserve food, but we're now able to use food additives to enrich and fortify our foods and drinks as well. Vitamins added to milk enhance its healthiness. Probiotics added to yogurts aid in digestion. Natural colors added to whole grain cereals make them fun and appealing.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 34,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405885,
    "lesson_id": 385,
    "title": "Elkhorn Coral",
    "content": "The oceans are changing. You can't tell by standing on a beach and watching waves roll in. But ocean water is becoming more acidic, experiments now show. One vulnerable animal is the Elkhorn coral, which is found throughout the Caribbean Sea. Elkhorn coral used to be easy to find in shallow water. Now it's an endangered species. In the last thirty years, many populations of Elkhorn coral have collapsed. Disease outbreaks, hurricanes, and elevated temperatures may all have played a role. Scientists are working on ways to save the coral, but they still have a long way to go. The coral may face yet another threat. In more acidic waters, Elkhorn coral is less successful at reproducing.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 35,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405886,
    "lesson_id": 385,
    "title": "Music to Tame Animals",
    "content": "Can music tame the wild beast? Can it hush puppies and calm kittens? A veterinarian thinks so. The vet has put music in over one thousand animal shelters and says it calms dogs and cats. Moreover, it even cuts down on barking. The vet started the nonprofit rescue animal project nearly four years ago. She asked artists around the world to donate dog-and-cat-friendly music. The result was an MP3 player packed with thirty hours of classics. The classics include music by Beethoven, Mozart, and Chopin. There were nursery rhymes like Three Blind Mice, as well as harps, pianos, and violins copying the sound of ocean waves and gentle breezes. These are given free to animal shelters. They are also given to sanctuaries and spay & neuter clinics.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 36,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405887,
    "lesson_id": 385,
    "title": "Animal Therapy",
    "content": "Studies conducted on Alzheimer's patients showed that providing dog therapy for one hour a day for four consecutive days reduced the apathy the patients had for their lives. In addition, other pet therapy, such as the use of aquariums, was shown to increase appetite and reduce aggression in patients with dementia. Animals of all sorts provide health benefits, not just domesticated pets. A ten-year-old boy with cerebral palsy was allowed to interact with a tame elephant over a period of time. The biological response to these episodes was an improved outlook on life and a chemical change in serotonin levels.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 37,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405888,
    "lesson_id": 385,
    "title": "Jewelry",
    "content": "Jewelry is any object other than clothes that is worn to decorate the body. People use many different materials in making jewelry. Fine jewelry is made of valuable metals, such as gold and silver, and beautiful stones called gems. Jewelry that is made of plastic, steel, ceramics, glass, or other less costly materials is called costume jewelry. People who still live as their ancient ancestors did make jewelry from bone, claws, animal hair, wood, and shells. People wear jewelry for many reasons. Kings, queens, and other leaders have often worn fine jewelry at important ceremonies and events. Some people wear jewelry for religious reasons.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 38,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405889,
    "lesson_id": 385,
    "title": "Queen Nefertiti",
    "content": "The ancient Egyptian Queen Nefertiti has long been at the center of a mystery. For years, archaeologists have wondered where her tomb might be hidden. Nefertiti belonged to the family line of the famous King Tutankhamun, better known as King Tut. Indeed, some believe she was Tut's mother. While the other royals in her line are all accounted for, Nefertiti is still missing. Now, however, an archaeologist claims to have found her secret tomb. He says it is in the Valley of the Kings, hidden just beyond a wall near the resting place of Tut. His theory is based on a detailed study of the walls of Tutankhamun's tomb. Using radar scans, he was able to see what the walls looked like beneath their layers of paint.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 39,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405890,
    "lesson_id": 385,
    "title": "Photography Explained",
    "content": "Using a camera to take photographs is called photography. A photograph is an image, or picture, that has been captured on film or some other material. People who take pictures are called photographers. Photography is a useful and effective form of communication. Photographs give information about people, places, objects, and events that words may not be able to describe. For over 200 years, newspapers and magazines around the world have printed photographs of interesting people and events. Advertisers and other businesses use photography to show people their products. Scientists, doctors, and police officers use photography to record important information.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 40,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405891,
    "lesson_id": 385,
    "title": "Paintball",
    "content": "Splat! What just hit me? Where did it come from? Welcome to the world of paintball! You were just hit (or marked) by a small round colorful object, about 0.68 inches in diameter, called a paintball. This is the size of your basic paintball. A basic paintball is filled with a water-soluble dye encapsulated in gelatin and comes in nice bright colors or in eco-friendly basic green. Put this little round colorful ball in a device called a marker and you have the beginnings of an experience you will never forget. The game of paintball!",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 41,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405892,
    "lesson_id": 385,
    "title": "Volcanic Eruption",
    "content": "During a volcanic eruption, hot melted rock, called magma, escapes from a vent or opening on the Earth's surface or crust. Magma released from a volcano is known as lava. It glows red as it flows out of the volcano's opening. As it cools, it hardens into rock. Strong volcanic eruptions throw bits of magma into the air. These bits cool into tiny pieces of rock, called volcanic dust or volcanic ash. The wind can carry volcanic dust thousands of miles away. Volcanic ash can coat the land for miles around a volcano. Steam and poisonous gases also escape from volcanoes. Sometimes these gases are mixed with ash and other hot debris. This mixture travels outward in destructive fiery clouds, called pyroclastic flows.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 42,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405893,
    "lesson_id": 385,
    "title": "Rhino Poachers",
    "content": "South Africa is home to most of the world's rhinos. However, the country has a big problem with poachers. Hunters killed more than twelve thousand of the country's rhinos last year and are killing them at a high rate this year to meet rising demand for their horns in parts of Asia. The buyers believe rhino horn, which is ground into powder, works as medicine. There is no scientific evidence to back up that idea. The horn is made of keratin, a protein also found in human fingernails. South Africa's national parks service rescued sixteen rhino orphans last year. A dozen were put in expert care. Four others were placed in government-run enclosures with female rhinos who act as mothers. The goal is to have the orphans return back to the rhino population in the wild.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 43,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405894,
    "lesson_id": 385,
    "title": "Spa Treatment",
    "content": "In today's increasingly hectic and stressful world, getting a spa treatment is sometimes one of the most therapeutic things an individual can enjoy. The relaxation and peaceful environment associated with a spa can allow a person to regain their sense of self and feeling of overall peace. From suntanning to massages and other therapeutic modalities, spas offer a unique opportunity to re-energize and reinvigorate the human body. Because spa treatments are becoming so popular, today there is an increasing number of spas that now offer flat monthly-fee-based services. This type of service makes good sense for those wishing to make spa treatments a regular and routine part of their life.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 44,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405895,
    "lesson_id": 385,
    "title": "Allergy or Sickness",
    "content": "When spring and summer creep up on us, we often don't know if what we're experiencing are allergies or basic end-of-flu-season ailments. There are a number of ways to recognize allergy symptoms and differentiate between being sick and having an allergic reaction. The reason why it's important to know the difference is because allergic reactions can run the gamut from the very mild and up to life-threatening symptoms so you need to know which kind you experience. A few surefire symptoms of allergic reactions are as follows: rashes, itchy eyes, nasal congestion, itchiness, difficulty breathing, cramps, vomiting, and dizziness.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 45,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405896,
    "lesson_id": 385,
    "title": "Galaxies",
    "content": "A galaxy is a group of stars, clouds of gas, and dust particles that move together through the universe. There are billions of galaxies in the universe. They probably formed billions of years ago, soon after the universe began. The sun, Earth, and the other planets of the solar system are part of the Milky Way galaxy. Most galaxies move through the universe as part of clusters, or groups, of galaxies. The Milky Way is at one end of a cluster called the Local Group. It includes about forty galaxies. The largest galaxy in the Local Group is the Andromeda Galaxy. Galaxies are divided into three main categories based on their shapes: spiral, elliptical, and irregular.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 46,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405897,
    "lesson_id": 385,
    "title": "Giant Squid",
    "content": "Resembling huge, squishy darts with tentacles, giant squid live in the darkest depths of the ocean. People seldom see these mysterious creatures but scientists just got to know the animals much better. In a study published in March, researchers clear up a long-standing mystery about how closely these animals are related. They find the colossal creatures belong to a single global species. A species is a group of organisms that are similar enough to breed with each other. Until now, scientists had thought that giant squid belonged to three different species. One species lived in the North Atlantic Ocean, another in southern oceans, and a third in waters near Japan.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 47,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405898,
    "lesson_id": 385,
    "title": "Death Valley",
    "content": "Death Valley deserves its name. It is a sunburnt land of salt flats, bad water, and scorching sand. This parched place is the hottest, driest spot in North America. However, it has not always been a desert wasteland. It was once a lake. The climate was much wetter. The land nearby was rich with life. The valley was still a lake when the first Native Americans arrived about 10,000 years ago. About 1000 years ago, the ancestors of today's Timbisha Shoshone people came to the valley. Over time, the climate changed. Temperatures rose. Less rain fell. The lake dried up. Only a few freshwater springs remained in the foothills, mountains, and valley.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 48,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405899,
    "lesson_id": 385,
    "title": "Putting Out a Flame",
    "content": "Why does blowing on a flame make it go out? There could be a few different reasons. Your breath has a lot of carbon dioxide. When you blow on a flame, the carbon dioxide pushes oxygen out of the way and the flame goes out. Your breath blows away some of the hot air around the flame. If the liquid wax cools down enough, it can't turn into a gas. Without wax gas, the flame won't burn. Your breath blows some of the wax gas away. Without this fuel, the flame will go out. Why does a flame have different colors? The colors of a flame are caused by bits of wax molecules that didn't get completely reacted. These glow a particular color when they reach a certain temperature. Since different parts of the flame have different temperatures, these bits of wax molecules make those areas of the flame glow with different colors.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 49,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405900,
    "lesson_id": 385,
    "title": "Gamma Rays",
    "content": "Gamma-ray bursts are flashes of gamma rays associated with extremely energetic explosions that have been observed in distant galaxies. They are the most luminous electromagnetic events known to occur in the universe. Bursts can last from ten milliseconds to several minutes, although a typical burst lasts between 20 to 40 seconds. The initial burst is usually followed by a longer-lived afterglow emitted at extended wavelengths. Most observed GRBs are believed to consist of a narrow beam of intense radiation released during a supernova event as a rapidly-rotating, high-mass star collapses to form a neutron star, quark star, or black hole.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 50,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405901,
    "lesson_id": 385,
    "title": "Stressful Food",
    "content": "The more uncomfortable you start to feel, the more stress starts to come on. Choose less salty snacks, like low-salt pretzels or even a low-salt version of your favorite potato chip. Junk food, in general, is considered stress-inducing and poor in nutritional components. When your body doesn't get enough of the minerals and nutrients it requires, its chances of being able to handle stress are greatly lowered. Eat yourself into a healthy state instead of toward a stressful one. Watch what you eat and stress will become more of a minor annoyance rather than a pending catastrophe in your life!",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 51,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 405902,
    "lesson_id": 385,
    "title": "Gardens",
    "content": "The type of garden you choose will depend on several factors. If you live in an apartment, it may be impossible for you to have a large vegetable garden no matter how much you may desire one. If you work 60 hours per week, caring for a very large rose garden could prove to be a little too much to handle. If you're confined to a wheelchair, taking care of a complex outdoor garden may be a bit beyond your capabilities. Ask yourself: how much space do I have available for gardening? How much time do I have to care for my plants? How physically capable am I to care for my garden?",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 52,
    "lesson_screen_content_id": ""
},
{
    "lesson_screen_id": 5408870,
    "lesson_id": 385,
    "title": "Highway Driving Tips",
    "content": "When you're on the highway, use cruise control, which helps maintain a constant speed. Use the highest gear possible and overdrive gears if you have them. The faster an engine is turning, the more gas you're using. Pay attention to your tachometer. Plus, a slower turning engine means less friction and engine wear. Avoid excessive idling. Idling gets zero miles per gallon. It doesn't get much worse than that. If you're stopped for a train or backed up in a fast food take-out line or waiting for a drive-thru bank teller, stop your engine if you're going to be idling for more than 30 seconds.",
    "intro": "",
    "new_key": "",
    "settings": "",
    "screen_type": "standard",
    "dictation_type": "words",
    "display_order": 53,
    "lesson_screen_content_id": ""
}
];